In [90]:
import torch

An important note one referencing and copying!
When working with a tensor the DEFAULT operations are copy operations,, i.e new memory is allocated for the object
we performed the operation on
But when we use a method of the tensor class that has an underscore, this references the original memeory address, and hence
modifies that value with our operation, this is kind of operation is called an 'in-shap' operation

In [91]:
# To illustrate the copy aspect

t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

t.neg()

# Our tensor stays positive even after applying the negative element-wise operator
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [92]:
# To illustrate the in place operation

t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

t.neg_()

# t stays negative after the operation
t

tensor([[-1., -1., -1., -1.],
        [-2., -2., -2., -2.],
        [-3., -3., -3., -3.]])

Tensor Ops can be broken down to 3 categories:

1. Shaping Operations
2. Element-Wise Operations
3. Reduction Operations
4. Access Operations

In [93]:
t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

In [94]:
# Shape determination
t.shape

torch.Size([3, 4])

In [95]:
# Rank Determination
len(t.shape)

2

In [96]:
# Element calculation
torch.tensor(t.shape).prod()
# or 
t.numel()

12

Shaping Operations manipulate the axes containing our elements as a means of organizing the tensor,
such as when we take images and add axes for color chanels, batch sizes, etc.
Reshaping a individual tensor retains the number of elements, but can changes the number of axes and ranks (reshape, squeeze unsqueez, flatten)
Combining multiple tensors changes all three aspects (cat, stack)

In [97]:
# Without changing the rank. Using -1 lets pytorch calculate the complementary number, if possible
t.reshape(-1, 2).shape
t.reshape(-1,1).shape
t.reshape(-1,12).shape

torch.Size([1, 12])

In [98]:
# Squeezing removes all axes that have a length of 1
t.reshape(-1,12).squeeze().shape

torch.Size([12])

In [99]:
# Unsqueezing inversely add an axis of length 1
t.reshape(-1,12).unsqueeze(dim=0).shape

torch.Size([1, 1, 12])

In [100]:
# flattening places all elements on one axis
t.flatten().shape

torch.Size([12])

Lets now talk about 'cat' and 'stack' operations.

Concatenate or cat, joins a sequence of tensors along an <b>existing axis</b>

Stacking joins a sequence of tensors along a <b>new axis</b>

Lets reinforce the importance of this with our go to example of working with image data:

1. A single image has three dimensions [channel, height, width], now suppose we had three images and wanted to create a batch with them, this would require a new axis
    such that the result is [batch, channel, height , width]. To add that new channel, we need to use <b>stack</b>

2. Now that we have our new batch dimension, we would like to concatenate the images together to create a batch size of 3, since we already have our correct dimensions
    from the first step, we can use <b>cat</b>

Now everytime we wanted to add new images that have [channel, height, width]. We will need to follow steps 1 & 2 respectively

In [101]:
t1 =torch.tensor([1,1,1])

In [102]:
# recall our unsqueeze operation, we will use this shortly
print(t1.unsqueeze(dim=0))
t1.unsqueeze(dim=0).shape

tensor([[1, 1, 1]])


torch.Size([1, 3])

In [103]:
# recall our unsqueeze operation, we will use this shortly
print(t1.unsqueeze(dim=1))
t1.unsqueeze(dim=1).shape

tensor([[1],
        [1],
        [1]])


torch.Size([3, 1])

In [104]:
# Lets create three example tensors 
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [105]:
# Using our single first axis, we can cat the tensors together
torch.cat((t1,t2,t3), dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [106]:
# Lets now add a new axis at the first index using our stack function 
# the new axis
print(torch.stack((t1,t2,t3), dim=0))
torch.stack((t1,t2,t3), dim=0).shape

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


torch.Size([3, 3])

In [107]:
# what stack really does is unsqueeze the tensors individually then concatenate that result
# this is super useful for getting used to this operation

# In this case we turn the tensors in a [1,3] then cat them along the first axis
torch.cat(
    (t1.unsqueeze(dim=0),
    t2.unsqueeze(dim=0),
    t3.unsqueeze(dim=0)), dim=0
) 

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [108]:
# Lets now stack our three tensors along the first dimension
print(torch.stack((t1,t2,t3), dim=1))
torch.stack((t1,t2,t3), dim=1).shape

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


torch.Size([3, 3])

In [109]:
# Lets illustrate this with our cat + unsqueeze combo

# In this case we turn the tensors in a [3,1] then cat them along the first axis
torch.cat(
    (t1.unsqueeze(dim=1),
    t2.unsqueeze(dim=1),
    t3.unsqueeze(dim=1)), dim=1
) 


tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

Element-wise operations focus on the specific elements are within the tensor, for these operations, the tensors
should have the same shape, and implicitly, the same elements. Examples of these are arithmetic operations (add, sub, mul, etc..)

In [110]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print('t1:',t1)
print('t2:',t2)
t3 = t1+t2
print('sum:', t3)

t1: tensor([[0.1483, 0.7593],
        [0.9770, 0.4834]])
t2: tensor([[0.5882, 0.2212],
        [0.1095, 0.1478]])
sum: tensor([[0.7365, 0.9804],
        [1.0864, 0.6312]])


An important concept in element-wise operations is called <b>broadcasting</b>, I'll leave a "todo" here to expand on the topic is a huge barrier between the newbies and the pros, and in essense, save a ton on processing and programming, since this
would normally be done via a for loop.

This knowledge is going to be very handy during data preparation and will be seen more in normalization techniques

see: https://deeplizard.com/learn/video/6_33ulFDuCg

In [111]:
# Here is the first example of broadcasting, the lower rank tensor, 2, is broadcasted to achieve the shape of 
# the larger tensor t1
t_broad = t1 +2
print(t_broad)

tensor([[2.1483, 2.7593],
        [2.9770, 2.4834]])


In [112]:
# We can also use comparison operations

In [113]:
t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

In [114]:
t.eq(1)

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [115]:
#Less than or equal
t.le(2)

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False]])

In [116]:
# greater than
t.gt(2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])

In [117]:
# greater or equal
t.ge(2)

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [118]:
# These are a few examples, a important point to note is that these operations are easily computed
# using broadcasting

In [119]:
# We can also perform basic functions
t.abs()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [120]:
t.sqrt()

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.7321, 1.7321, 1.7321, 1.7321]])

In [121]:
t.neg()

tensor([[-1., -1., -1., -1.],
        [-2., -2., -2., -2.],
        [-3., -3., -3., -3.]])

In [122]:
t.neg().abs()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

Lastly, we take a look at reduction operations. As the name implies, reduction operations 
reduce the tensor

In [123]:
# Good examples are the sum, mean, product, and std deviations

print(t.sum())
print(t.mean())
print(t.prod())
print(t.std())

tensor(24.)
tensor(2.)
tensor(1296.)
tensor(0.8528)


In [124]:
# Where things get intersting (and a little tricky), is when we perform reduction operations
# along certain axes.

# Here we are summing across the 0 axis = the arrays
print(t.sum(dim=0))

# Here we are summing across the first axis = the numbers in the arrays
print(t.sum(dim=1))

tensor([6., 6., 6., 6.])
tensor([ 4.,  8., 12.])


In [125]:
# Another extremely popular operation is called 'argmax', argmax returns the index of the largest value
# of the flattened version of the tensor, which is the first three that pops up

# We normally will use argmax to determine the classification in the output layer
print(t.argmax())

# Using the 'max' method shows both the values and the indexes
print(t.max())


# To drive that point home
print(t.flatten())




tensor(8)
tensor(3.)
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [126]:
# We can perform this operation along a particular axis as well
# Lets create a tensor that we can see the results a little more clearly with

t = torch.rand(3,3)

t

tensor([[0.0885, 0.2731, 0.8982],
        [0.0215, 0.0393, 0.0474],
        [0.8296, 0.7881, 0.8130]])

In [127]:
# Using the first dimension, we get the maximum value as it pertains to
# a column, where the value is the index of the columns
print(t.argmax(dim=0))

# Using the 'max' method shows both the values and the indexes
print(t.max(dim=0))

tensor([2, 2, 0])
torch.return_types.max(
values=tensor([0.8296, 0.7881, 0.8982]),
indices=tensor([2, 2, 0]))


In [128]:
# Using the second dimension, we are given the maximum value of each array along with the index
# of that value along that array
print(t.argmax(dim=1))
print(t.max(dim=1))


tensor([2, 2, 0])
torch.return_types.max(
values=tensor([0.8982, 0.0474, 0.8296]),
indices=tensor([2, 2, 0]))


Lastly we have Access operations, simply put, access operations pertain to accessing and extracting the value at a tensor
The 'item' and 'toList' methods are two methods that can be used turn the tensor into the actual value type ex. ints, floats etc.

In [129]:

# item pertains to scalar tensors (rank 1)
print(t.mean())
print(t.mean().item())


# to list is applicable to greater rank tensors
print(t.mean(dim=0))
print(t.mean(dim=0).tolist())

# We can also use the numpy method for both of these cases to extract a numpy array
print(t.mean().numpy())
print(t.mean(dim=0).numpy())


tensor(0.4221)
0.4220750033855438
tensor([0.3132, 0.3668, 0.5862])
[0.3131769299507141, 0.3668476641178131, 0.5862004160881042]
0.422075
[0.31317693 0.36684766 0.5862004 ]
