In [122]:
import torch

An important note one referencing and copying!
When working with a tensor the DEFAULT operations are copy operations,, i.e new memory is allocated for the object
we performed the operation on
But when we use a method of the tensor class that has an underscore, this references the original memeory address, and hence
modifies that value with our operation, this is kind of operation is called an 'in-shap' operation

In [123]:
# To illustrate the copy aspect

t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

t.neg()

# Our tensor stays positive even after applying the negative element-wise operator
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [124]:
# To illustrate the in place operation

t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

t.neg_()

# t stays negative after the operation
t

tensor([[-1., -1., -1., -1.],
        [-2., -2., -2., -2.],
        [-3., -3., -3., -3.]])

Tensor Ops can be broken down to 3 categories:

1. Shaping Operations
2. Element-Wise Operations
3. Reduction Operations
4. Access Operations

In [125]:
t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

In [126]:
# Shape determination
t.shape

torch.Size([3, 4])

In [127]:
# Rank Determination
len(t.shape)

2

In [128]:
# Element calculation
torch.tensor(t.shape).prod()
# or 
t.numel()

12

Shaping Operations manipulate the axes containing our elements as a means of organizing the tensor,
such as when we take images and add axes for color chanels, batch sizes, etc.
Reshaping a individual tensor retains the number of elements, but can changes the number of axes and ranks (reshape, squeeze unsqueez, flatten)
Combining multiple tensors changes all three aspects (cat, stack)

In [129]:
# Without changing the rank. Using -1 lets pytorch calculate the complementary number, if possible
t.reshape(-1, 2).shape
t.reshape(-1,1).shape
t.reshape(-1,12).shape

torch.Size([1, 12])

In [130]:
# Squeezing removes all axes that have a length of 1
t.reshape(-1,12).squeeze().shape

torch.Size([12])

In [131]:
# Unsqueezing inversely add an axis of length 1
t.reshape(-1,12).unsqueeze(dim=0).shape

torch.Size([1, 1, 12])

In [132]:
# flattening places all elements on one axis
t.flatten().shape

torch.Size([12])

Element-wise operations focus on the specific elements are within the tensor, for these operations, the tensors
should have the same shape, and implicitly, the same elements. Examples of these are arithmetic operations (add, sub, mul, etc..)

In [133]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print('t1:',t1)
print('t2:',t2)
t3 = t1+t2
print('sum:', t3)

t1: tensor([[0.1692, 0.9531],
        [0.4031, 0.2568]])
t2: tensor([[0.8602, 0.8811],
        [0.0907, 0.8114]])
sum: tensor([[1.0294, 1.8342],
        [0.4938, 1.0682]])


An important concept in element-wise operations is called <b>broadcasting</b>, I'll leave a "todo" here to expand on the topic is a huge barrier between the newbies and the pros, and in essense, save a ton on processing and programming, since this
would normally be done via a for loop.

This knowledge is going to be very handy during data preparation and will be seen more in normalization techniques

see: https://deeplizard.com/learn/video/6_33ulFDuCg

In [134]:
# Here is the first example of broadcasting, the lower rank tensor, 2, is broadcasted to achieve the shape of 
# the larger tensor t1
t_broad = t1 +2
print(t_broad)

tensor([[2.1692, 2.9531],
        [2.4031, 2.2568]])


In [135]:
# We can also use comparison operations

In [136]:
t = torch.tensor([
  [1,1,1,1],
  [2,2,2,2],
  [3,3,3,3]
],dtype=torch.float32)

In [137]:
t.eq(1)

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [138]:
#Less than or equal
t.le(2)

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False]])

In [139]:
# greater than
t.gt(2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])

In [140]:
# greater or equal
t.ge(2)

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [141]:
# These are a few examples, a important point to note is that these operations are easily computed
# using broadcasting

In [142]:
# We can also perform basic functions
t.abs()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [143]:
t.sqrt()

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 1.4142, 1.4142, 1.4142],
        [1.7321, 1.7321, 1.7321, 1.7321]])

In [144]:
t.neg()

tensor([[-1., -1., -1., -1.],
        [-2., -2., -2., -2.],
        [-3., -3., -3., -3.]])

In [145]:
t.neg().abs()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

Lastly, we take a look at reduction operations. As the name implies, reduction operations 
reduce the tensor

In [146]:
# Good examples are the sum, mean, product, and std deviations

print(t.sum())
print(t.mean())
print(t.prod())
print(t.std())

tensor(24.)
tensor(2.)
tensor(1296.)
tensor(0.8528)


In [147]:
# Where things get intersting (and a little tricky), is when we perform reduction operations
# along certain axes.

# Here we are summing across the 0 axis = the arrays
print(t.sum(dim=0))

# Here we are summing across the first axis = the numbers in the arrays
print(t.sum(dim=1))

tensor([6., 6., 6., 6.])
tensor([ 4.,  8., 12.])


In [148]:
# Another extremely popular operation is called 'argmax', argmax returns the index of the largest value
# of the flattened version of the tensor, which is the first three that pops up

# We normally will use argmax to determine the classification in the output layer
print(t.argmax())

# Using the 'max' method shows both the values and the indexes
print(t.max())


# To drive that point home
print(t.flatten())




tensor(8)
tensor(3.)
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [149]:
# We can perform this operation along a particular axis as well
# Lets create a tensor that we can see the results a little more clearly with

t = torch.rand(3,3)

t

tensor([[0.2207, 0.2967, 0.6653],
        [0.0569, 0.3926, 0.3455],
        [0.8096, 0.1436, 0.6295]])

In [150]:
# Using the first dimension, we get the maximum value as it pertains to
# a column, where the value is the index of the columns
print(t.argmax(dim=0))

# Using the 'max' method shows both the values and the indexes
print(t.max(dim=0))

tensor([2, 1, 0])
torch.return_types.max(
values=tensor([0.8096, 0.3926, 0.6653]),
indices=tensor([2, 1, 0]))


In [151]:
# Using the second dimension, we are given the maximum value of each array along with the index
# of that value along that array
print(t.argmax(dim=1))
print(t.max(dim=1))


tensor([2, 1, 0])
torch.return_types.max(
values=tensor([0.6653, 0.3926, 0.8096]),
indices=tensor([2, 1, 0]))


In [164]:
# the 'item' and 'toList' methods are two methods that can be used turn the tensor into
# the actual number type

# item pertains to scalar tensors (rank 1)
print(t.mean())
print(t.mean().item())


# to list is applicable to greater rank tensors
print(t.mean(dim=0))
print(t.mean(dim=0).tolist())

# We can also use the numpy method for both of these cases to extract a numpy array
print(t.mean().numpy())
print(t.mean(dim=0).numpy())


tensor(0.3956)
0.39560940861701965
tensor([0.3624, 0.2776, 0.5468])
[0.36241066455841064, 0.2776392996311188, 0.54677814245224]
0.3956094
[0.36241066 0.2776393  0.54677814]
